### ISSUE TITLE
calico IP-in-IP tunnel device uses incorrect MTU in GCE

### ISSUE THREAD

**Issue by Symmetric** [projectcalico/calico-docker#415] opened 2015-08-04 01:05 UTC
The tunl0 device uses MTU 1480 unconditionally. In GCE, the network MTU is 1460, so the correct MTU for the tunl0 device is 1440 in this environment.

With the incorrect value of 1480, packets are dropped after encapsulation, but before being transmitted on the VM's external interface. One might expect the kernel to generate an ICMP "fragmentation required" in this case, but that does not happen.

This issue is exacerbated by the kernel's TSO/GSO function, which can coalesce outbound packets into a single jumbo frame (to be segmented by the NIC) to improve transmission rates. This feature (enabled by default on most kernels, including GCE's Ubuntu and CoreOS images) can cause a burst of small packets (e.g. those produced by a traffic generator) to be glued into a single MTU-sized packet, which since the MTU is incorrect, will also be dropped after encapsulation.

Cheapest fix would be to pick an arbitrary number <= 1440 and use that as the tunl0 MTU in all cases. Could alternatively try to determine the value dynamically by inspecting the interfaces on the machine -- but that could be tricky. pMTU detection is available in the kernel, but this seems to be discouraged for security reasons.

**Comment by plwhite** [comment] 2015-08-04 08:40
Actually, a trivial way of doing this would be to have this a configurable parameter in Felix. I might be misunderstanding, but shouldn't this issue be against calico, not calico-docker? Felix creates the tunnel, so changing this is just a couple of lines in Felix code.

**Comment by lxpollitt** [comment] 2015-08-04 14:47
Configurable parameter in Felix sounds sensible, but it's only half of the problem.  We also need to provide a way of either automatically configuring it or providing calicoctl commands to to so or similar.

**Comment by Symmetric** [comment] 2015-08-04 16:13
Yep, good point @plwhite ; wasn't sure if there was docker-specific code in this situation.

Closed in favour of https://github.com/projectcalico/calico/issues/756.

**Comment by Symmetric** [comment] 2015-08-04 16:28
Actually this should be open for the calicoctl piece

**Comment by plwhite** [comment] 2015-08-05 08:32
The solution Shaun came up with was to set the default MTU low enough to work with GCE. Thus although you might want to allow tuning it, you don't absolutely have to in order to get IP in IP to work.

**Comment by Symmetric** [comment] 2015-08-06 15:58
Also, note that the interface created by `calicoctl container add` (as of calicoctl v0.5.2) uses MTU 1500. This didn't seem to break things (i.e. just setting the correct MTU on the tunl0 adapter stopped the packet drops), but I suspect that we want to use the same MTU for the calico interface too.

**Comment by TrimBiggs** [comment] 2015-08-06 18:02
It looks like the change to felix fixes the actual bug here.  I am closing this issue in favor of adding the additional calicoctl piece as a separate backlog item, since it is a different task and not a bug.

**Closed by TrimBiggs** 2015-08-06 18:02 UTC
Labels: bug

**Comment by Symmetric** [comment] 2015-08-06 18:59
I'll leave this here; just did some quick perf profiling and there doesn't seem to be a significant effect from reducing the container MTU from 1500 to 1440.

```
(container mtu 1500)
PKT_SIZE,THROUGHPUT,THROUGHPUT_UNITS,MEAN_LATENCY,MIN_LATENCY,MAX_LATENCY,P50_LATENCY,P90_LATENCY,P99_LATENCY,STDDEV_LATENCY,LOCAL_CPU_UTIL
64,78.40,10^6bits/s,6.25,0,15331,6,14,29,12.56,15.65,
128,131.53,10^6bits/s,7.47,0,15624,7,16,32,14.46,15.23,
256,257.94,10^6bits/s,7.64,0,204188,7,15,31,59.73,15.74,
512,680.82,10^6bits/s,5.71,0,15892,1,12,31,20.10,15.26,
1024,1789.11,10^6bits/s,4.36,0,206528,1,9,25,93.06,13.92,
1500,2526.85,10^6bits/s,4.56,0,19935,1,9,21,98.84,13.32,
3000,2580.07,10^6bits/s,9.06,0,23238,1,12,35,133.56,12.84,
6000,3240.70,10^6bits/s,14.59,0,21177,1,12,38,215.08,10.65,
12000,3280.06,10^6bits/s,29.03,1,17368,2,15,93,340.95,9.74,
24000,3266.98,10^6bits/s,58.47,1,18657,3,24,2675,496.38,9.65,
48000,3273.55,10^6bits/s,116.91,4,22644,6,41,4054,702.40,9.33,

(container mtu 1440)
PKT_SIZE,THROUGHPUT,THROUGHPUT_UNITS,MEAN_LATENCY,MIN_LATENCY,MAX_LATENCY,P50_LATENCY,P90_LATENCY,P99_LATENCY,STDDEV_LATENCY,LOCAL_CPU_UTIL
64,70.77,10^6bits/s,6.95,0,189752,7,15,31,51.80,15.17,
128,122.77,10^6bits/s,8.01,0,193959,7,17,33,57.70,14.86,
256,270.42,10^6bits/s,7.28,0,14137,7,15,30,16.44,15.94,
512,588.78,10^6bits/s,6.66,0,179853,7,12,29,52.03,16.27,
1024,1582.01,10^6bits/s,4.94,0,18528,1,10,27,65.71,14.34,
1500,2256.34,10^6bits/s,5.11,0,17589,1,10,23,97.22,13.88,
3000,2784.27,10^6bits/s,8.40,0,18279,1,11,32,143.95,11.94,
6000,3165.98,10^6bits/s,14.93,0,210602,1,12,36,238.77,10.60,
12000,3241.42,10^6bits/s,29.36,1,19791,2,17,85,342.04,10.47,
24000,3300.99,10^6bits/s,57.87,1,20090,3,19,2801,483.40,8.78,
48000,3104.06,10^6bits/s,123.32,4,27531,6,41,4377,777.06,9.70,
```

**Comment by vinayk06** [comment] 2017-04-05 17:10
how to configure felix I am using calico/node:v1.1.0
