### ISSUE TITLE
remove pool,but  something   relationship of pool    still  exist  in the etcd .

### ISSUE THREAD

**Issue by jaywayjayway** [projectcalico/calico-docker#674] opened 2015-12-11 09:32 UTC
I show my environment ：
-  two nodes: hostname with  node1, controller 
- node1's IPaddress  `10.10.0.7`
- controller's IPaddress `10.10.0.5`
- kubernetes cluster with calico_kubernetes (all are right)

starting  container  named calico-node  using  `calicoctl  node --ip xxx ` on above the nodes.And it will create pool  `192.168.0.0/16`,as show below:

```
[root@controller calico_kubernetes]# calicoctl pool show 
+----------------+--------------+
|   IPv4 CIDR    |   Options    |
+----------------+--------------+
| 192.168.0.0/16 |              |
+----------------+--------------+
+--------------------------+---------+
|        IPv6 CIDR         | Options |
+--------------------------+---------+
| fd80:24e2:f998:72d6::/64 |         |
+--------------------------+---------+
```
then I use k8s to create two pods. the two pods then delete them .that's alway be OK .

ine the etcd ,there has something .

```
[root@controller calico_ctl]# etcdctl  ls  /calico/v1/ipam/v4/pool
/calico/v1/ipam/v4/pool/192.168.0.0-16

```

```
[root@controller calico_ctl]# etcdctl  get  /calico/ipam/v2/assignment/ipv4/block/192.168.0.0-26
{"attributes": [], "cidr": "192.168.0.0/26", "affinity": "host:node1", "allocations": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]}
```

```
[root@controller calico_ctl]# etcdctl  get  /calico/ipam/v2/assignment/ipv4/block/192.168.0.64-26
{"attributes": [], "cidr": "192.168.0.64/26", "affinity": "host:controller", "allocations": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]}
```

last , deleting pool with `calicoctl pool remove 192.168.0.0/16`. I think the values of `/calico/v1/ipam/v4/pool`,`/calico/ipam/v2/assignment/ipv4/block/`,should be deleted.But Actually,the last one  didn't be delete.

then I seach the source code, the function   of `delete pool ` is defineed in `pycalico/datastore.py`

```
    def remove_ip_pool(self, version, cidr):
        """
        Delete the given CIDR range from the list of pools.  If the pool does
        not exist, raise a KeyError.

        :param version: 4 for IPv4, 6 for IPv6
        :param cidr: IPNetwork object representing the pool
        :return: None
        """
        assert version in (4, 6)
        assert isinstance(cidr, IPNetwork)

        # Normalize to CIDR format (i.e. 10.1.1.1/8 goes to 10.0.0.0/8)
        cidr = cidr.cidr

        key = IP_POOL_KEY % {"version": str(version),
                             "pool": str(cidr).replace("/", "-")}
        try:
            self.etcd_client.delete(key)                            ###only delete the pool
        except EtcdKeyNotFound:
            # Re-raise with a better error message.
            raise KeyError("%s is not a configured IP pool." % cidr)

```

**Comment by robbrockbank** [comment] 2015-12-14 18:05
Hi @jaywayjayway 

Yes I agree.  There are a couple of issues related to dangling configuration with the IP Pools.  One is #519 in calico-docker and the other is issue 56 in libcalico.

We are thinking about the best way to fix this at the moment.

https://github.com/projectcalico/calico-docker/issues/519
https://github.com/projectcalico/libcalico/issues/56

I'm closing this issue since it is effectively a duplicate of issue 56 in libcalico.  I'll update that issue when we have a solution.  I'd suggest you watch that issue for updates.

If you think this issue covers a different scenario, reopen and let me know.

Thanks,

Rob

**Closed by robbrockbank** 2015-12-14 18:05 UTC
