### ISSUE TITLE
Issue with running Calico with libnetwork and coreos

### ISSUE THREAD

**Issue by smakam** [projectcalico/calico-docker#511] opened 2015-10-02 09:41 UTC
hi 
I followed the procedure here to install calico with libnetwork in coreos.
https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/VagrantCoreOS.md

Iam using coreos alpha 815.0.0 image with Vagrant and Virtualbox. I created 2 node cluster.

I was able to start calico with libnetwork. 
When I start the container, I get the following error:
core@calico-01 ~ $ /opt/bin/docker run --publish-service srvA.net1.calico --name workload-A -tid busybox
d9bb4f52ba24e30066de38713419eeab96370f58e33734e4b5dbe478cd417857
Error response from daemon: Cannot start container d9bb4f52ba24e30066de38713419eeab96370f58e33734e4b5dbe478cd417857: failed to set s
tatic route: &{172.17.8.101/32 1 <nil> 0}; rolled back

This is the docker version running:
core@calico-01 ~ $ /opt/bin/docker --version
Docker version 1.8.0-dev, build 3ee15ac, experimental

Any ideas?

Thanks
Sreenivas

**Comment by tomdee** [comment] 2015-10-02 16:21
@smakam Thanks for the bug report. 

This is a bug in our code. The problem is with line 110 in https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/libnetwork/cloud-config/user-data-first

The line needs to be replaced with 
```
wget https://experimental.docker.com/builds/Linux/x86_64/docker-latest
```

I'm not going to have a chance to test it myself today, but you're welcome to try :smile:

**Comment by smakam** [comment] 2015-10-02 17:17
@tomdee 
Thanks for your response.

i assume that we also need "mv docker-latest docker" since the next line does "chmod +x docker". 

Now, I see that docker service does not get started and i get the following error for docker.service:
Oct 02 17:12:11 calico-01 systemd[1]: Starting Docker Application Container Engine...
Oct 02 17:12:11 calico-01 docker[2151]: flag provided but not defined: --kv-store
Oct 02 17:12:11 calico-01 docker[2151]: See '/opt/bin/docker --help'.
Oct 02 17:12:11 calico-01 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVA
LIDARGUMENT
Oct 02 17:13:12 calico-01 calicoctl[2152]: Traceback (most recent call last):
Oct 02 17:13:12 calico-01 calicoctl[2152]: File "<string>", line 102, in <module>
Oct 02 17:13:12 calico-01 calicoctl[2152]: File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.check
system", line 46, in checksystem
Oct 02 17:13:12 calico-01 calicoctl[2152]: File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.check
system", line 69, in check_system
Oct 02 17:13:12 calico-01 calicoctl[2152]: File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.check
system", line 175, in _check_docker_version
Oct 02 17:13:12 calico-01 calicoctl[2152]: File "/code/build/calicoctl/out00-PYZ.pyz/docker.client",
line 1110, in version
Oct 02 17:13:12 calico-01 calicoctl[2152]: File "/code/build/calicoctl/out00-PYZ.pyz/docker.client",
line 106, in _get
Oct 02 17:13:12 calico-01 calicoctl[2152]: File "/code/build/calicoctl/out00-PYZ.pyz/requests.session
s", line 477, in get
Oct 02 17:13:12 calico-01 calicoctl[2152]: File "/code/build/calicoctl/out00-PYZ.pyz/requests.session
s", line 465, in request
Oct 02 17:13:12 calico-01 calicoctl[2152]: File "/code/build/calicoctl/out00-PYZ.pyz/requests.session
s", line 573, in send
Oct 02 17:13:12 calico-01 calicoctl[2152]: File "/code/build/calicoctl/out00-PYZ.pyz/requests.adapter
s", line 433, in send
Oct 02 17:13:12 calico-01 calicoctl[2152]: ReadTimeout: UnixHTTPConnectionPool(host='localhost', port
=None): Read timed out. (read timeout=60)
Oct 02 17:13:12 calico-01 calicoctl[2152]: Unexpected error executing command.
Oct 02 17:13:12 calico-01 systemd[1]: docker.service: Control process exited, code=exited status=1
Oct 02 17:13:12 calico-01 systemd[1]: Failed to start Docker Application Container Engine.
Oct 02 17:13:12 calico-01 systemd[1]: docker.service: Unit entered failed state.
Oct 02 17:13:12 calico-01 systemd[1]: docker.service: Failed with result 'exit-code'.

Also, I assume that the change you mentioned is also needed for user-data-others.

Thanks
Sreenivas

**Comment by tomdee** [comment] 2015-10-02 18:07
Good spot on the mv command. 

They've renamed that parameter to `--cluster-store=`. I think the format has also changed to require a `//` too

So, I think line 70 needs changing now (https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/libnetwork/cloud-config/user-data-first#L70) to

```
ExecStart=/opt/bin/docker --cluster-store=consul://$private_ipv4:8500 --daemon --host=fd:// $DOCKER_OPTS $DOCKER_OPT_BIP $DOCKER_OP
```

**Comment by tomdee** [comment] 2015-10-02 18:07
And yes to changing user-data-others

**Comment by smakam** [comment] 2015-10-03 04:51
hi @tomdee 
I made the following change in line 70:
/opt/bin/docker --cluster-store=consul://$private_ipv4:8500 --daemon --host=fd:// $DOCKE
R_OPTS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ

Now I get this error while starting calicoctl:
core@calico-01 ~ $ sudo calicoctl node --libnetwork
No IP provided. Using detected IP: 172.17.8.101
Unexpected error executing command.

Traceback (most recent call last):
  File "<string>", line 102, in <module>
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 182, in node
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 326, in node_start
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.utils.decorators", line 15, in wrapped
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 1065, in start
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 122, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("Cannot start container bcf5d4b275cbc8017839c86c3a
64e2277838f9f628e4a81e714539bae08cb706: [8] System error: stat /var/lib/docker/containers/bcf5d4b275c
bc8017839c86c3a64e2277838f9f628e4a81e714539bae08cb706/hosts: no such file or directory")

Looks like there are some incompatibilities with latest docker experimental version?

thanks
Sreenivas

**Comment by tomdee** [comment] 2015-10-05 20:11
Yes, looks like a docker problem. They're going to be merging a new libnetwork UX soon into docker and exiting experimental. It might be worth holding off a few days until things settle down.

**Comment by tomdee** [comment] 2015-10-08 16:58
@robbrockbank Did you have a branch that fixes this?

**Comment by smakam** [comment] 2015-10-12 10:50
hi folks
Any progress on this? Would this get fixed as part of official Docker release? Any idea when this is expected? 

Thanks
Sreenivas

**Comment by tomdee** [comment] 2015-10-12 16:07
Yes, it will be fixed as part of the docker 1.9 release (which is due on Oct 27 I believe).

If you want to try it out sooner, we'll be releasing a v0.8.0 version of Calico docker shortly - current work in progress is on this branch https://github.com/projectcalico/calico-docker/tree/v0.8.0-candidate

However, we only have it working on Ubuntu and not CoreOS.

**Comment by tomdee** [comment] 2015-10-12 16:23
I've raised an upstream bug to track this https://github.com/docker/docker/issues/16948

**Comment by robbrockbank** [comment] 2015-10-21 17:56
The v0.8.0 release was tested with CoreOS.  This should be working now.  Closing issue.

**Closed by robbrockbank** 2015-10-21 17:56 UTC
Labels: bug, libnetwork
