### ISSUE TITLE
Felix iptable configuration is gone

### ISSUE THREAD

**Issue by hectorj2f** [projectcalico/calico-docker#497] opened 2015-09-24 08:16 UTC
Hi guys,

I have a CoreOS cluster and we use fleet as scheduler. We figured it out that if for whatever reason the systemd unit that starts `calico-node` is restarted (possible reason fleet rescheduling, restarting of systemd-journald, ... kaos monkey). All the Felix iptable configuration of my containers in that host are GONE. That's bad... we expect `etcd` to have information about those containers, as their weren't affected by this restart operation. The container IPs remain the same, what is obvious.

An easy way to repro this issue is to start `calico.service` register some containers and then manually restart the systemd unit with calico
```
[Unit]
Description=calico
After=calico-installer.service

[Service]
EnvironmentFile=/etc/environment
Restart=on-failure
RestartSec=1s
StartLimitInterval=300s
StartLimitBurst=3
TimeoutStartSec=0
ExecStartPre=/bin/sh -c '/opt/bin/calicoctl checksystem --fix'
ExecStartPre=/bin/sh -c '/opt/bin/calicoctl node --ip=${COREOS_PRIVATE_IPV4} --node-image=registry.private/calico:0.6.0'
ExecStartPre=/bin/sh -c '/opt/bin/calicoctl pool add 172.16.0.0/16 --ipip --nat-outgoing'
ExecStart=/usr/bin/docker logs -f calico-node
SuccessExitStatus=2
ExecStop=/opt/bin/calicoctl node stop --force

[X-Fleet]
Global=true
```
Register some containers:
```
$ docker run --net=none --name workload-B -tid busybox
$ sudo calicoctl container add workload-B 172.16.1.221
$ sudo calicoctl container workload-B profile append ALL
```
Then restart systemd and...
$ systemctl restart calico.service

Do you any workaround to recover from this situation ? We are forced to re-register all the containers once again and that can become a nightmare if you have 1k of them.

**Comment by spikecurtis** [comment] 2015-09-28 19:10
@hectorj2f which version of `calicoctl` are you using?

**Comment by hectorj2f** [comment] 2015-09-28 19:33
I am using v0.6.0

**Comment by hectorj2f** [comment] 2015-09-29 09:15
@spikecurtis I use v0.6.0 :)

**Comment by tomdee** [comment] 2015-09-30 21:33
AFAIK, felix won't remove the IPTables rules when it exits. @fasaxc can you confirm?

I can't repro this problem manually. @hectorj2f Does my run through below capture the issue you're seeing?
```
gulfstream@gulfstream:~/calico-docker$ sudo dist/calicoctl endpoint show --detailed
+----------+-----------------+-------------+-------------+-----------+-----+----------+-------+
| Hostname | Orchestrator ID | Workload ID | Endpoint ID | Addresses | MAC | Profiles | State |
+----------+-----------------+-------------+-------------+-----------+-----+----------+-------+
+----------+-----------------+-------------+-------------+-----------+-----+----------+-------+

gulfstream@gulfstream:~/calico-docker$ docker run --net=none --name test1 -tid busybox
4897b346c3cb241f0cf9bae02485830962346f50bbd71e38a304e5dace11f26b
gulfstream@gulfstream:~/calico-docker$ docker run --net=none --name test2 -tid busybox
2ebd3bf0a9ecaa0dedf72ee582978d29df5fd75c7b6ce46ad219c7af8b1fde68
gulfstream@gulfstream:~/calico-docker$ dist/calicoctl profile add TEST
Created profile TEST
gulfstream@gulfstream:~/calico-docker$ sudo dist/calicoctl container add test1 192.168.0.1
gulfstream@gulfstream:~/calico-docker$ sudo dist/calicoctl container add test2 192.168.0.2
gulfstream@gulfstream:~/calico-docker$ sudo dist/calicoctl container test1 profile append TEST
Profiles TEST appended

gulfstream@gulfstream:~/calico-docker$ sudo dist/calicoctl container test2 profile append TEST
Profiles TEST appended

gulfstream@gulfstream:~/calico-docker$ docker exec test1 ping 192.168.0.2
PING 192.168.0.2 (192.168.0.2): 56 data bytes
64 bytes from 192.168.0.2: seq=0 ttl=63 time=0.146 ms
64 bytes from 192.168.0.2: seq=1 ttl=63 time=0.829 ms
^Cgulfstream@gulfstream:~/calico-dockersudo dist/calicoctl endpoint show --detailed
+------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+----------+--------+
|  Hostname  | Orchestrator ID |                           Workload ID                            |           Endpoint ID            |   Addresses    |        MAC        | Profiles | State  |
+------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+----------+--------+
| gulfstream |      docker     | 2ebd3bf0a9ecaa0dedf72ee582978d29df5fd75c7b6ce46ad219c7af8b1fde68 | f3aa163467b911e58d6d080027bf35cd | 192.168.0.2/32 | e2:47:52:bc:8a:fa |   TEST   | active |
| gulfstream |      docker     | 4897b346c3cb241f0cf9bae02485830962346f50bbd71e38a304e5dace11f26b | f13d1f5467b911e58d6d080027bf35cd | 192.168.0.1/32 | be:4e:43:0b:3d:dc |   TEST   | active |
+------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+----------+--------+

gulfstream@gulfstream:~/calico-docker$ sudo iptables-save
# Generated by iptables-save v1.4.21 on Wed Sep 30 14:28:17 2015
...snip...
-A felix-FORWARD -i cali+ -m conntrack --ctstate INVALID -j DROP
-A felix-FORWARD -o cali+ -m conntrack --ctstate INVALID -j DROP
-A felix-FORWARD -i cali+ -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
-A felix-FORWARD -o cali+ -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
-A felix-FORWARD -i cali+ -j felix-FROM-ENDPOINT
-A felix-FORWARD -o cali+ -j felix-TO-ENDPOINT
-A felix-FORWARD -i cali+ -j ACCEPT
-A felix-FORWARD -o cali+ -j ACCEPT
-A felix-FROM-ENDPOINT -i calif+ -g felix-FROM-EP-PFX-f
-A felix-FROM-ENDPOINT -j DROP
-A felix-FROM-EP-PFX-f -i calif3aa163467b -g felix-from-f3aa163467b
-A felix-FROM-EP-PFX-f -i calif13d1f5467b -g felix-from-f13d1f5467b
-A felix-FROM-EP-PFX-f -j DROP
...snip...
# Completed on Wed Sep 30 14:28:17 2015
gulfstream@gulfstream:~/calico-docker$ docker rm -f calico-node
calico-node
gulfstream@gulfstream:~/calico-docker$ sudo iptables-save
# Generated by iptables-save v1.4.21 on Wed Sep 30 14:28:34 2015
...snip...
-A felix-FORWARD -i cali+ -m conntrack --ctstate INVALID -j DROP
-A felix-FORWARD -o cali+ -m conntrack --ctstate INVALID -j DROP
-A felix-FORWARD -i cali+ -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
-A felix-FORWARD -o cali+ -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
-A felix-FORWARD -i cali+ -j felix-FROM-ENDPOINT
-A felix-FORWARD -o cali+ -j felix-TO-ENDPOINT
-A felix-FORWARD -i cali+ -j ACCEPT
-A felix-FORWARD -o cali+ -j ACCEPT
-A felix-FROM-ENDPOINT -i calif+ -g felix-FROM-EP-PFX-f
-A felix-FROM-ENDPOINT -j DROP
-A felix-FROM-EP-PFX-f -i calif3aa163467b -g felix-from-f3aa163467b
-A felix-FROM-EP-PFX-f -i calif13d1f5467b -g felix-from-f13d1f5467b
-A felix-FROM-EP-PFX-f -j DROP
...snip...
# Completed on Wed Sep 30 14:28:36 2015
gulfstream@gulfstream:~/calico-docker$ docker exec test1 ping 192.168.0.2
PING 192.168.0.2 (192.168.0.2): 56 data bytes
64 bytes from 192.168.0.2: seq=0 ttl=63 time=0.202 ms
64 bytes from 192.168.0.2: seq=1 ttl=63 time=0.158 ms
^Cgulfstream@gulfstream:~/calico-docker
gulfstream@gulfstream:~/calico-docker$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
2ebd3bf0a9ec        busybox             "/bin/sh"                3 minutes ago       Up 3 minutes                            test2
4897b346c3cb        busybox             "/bin/sh"                3 minutes ago       Up 3 minutes                            test1
f4414c60d7c7        busybox             "/bin/sh"                33 minutes ago      Up 33 minutes                           test
47584d8de261        quay.io/core        "/etcd --advertise-cl"   24 hours ago        Up 24 hours                             calico-etcd
gulfstream@gulfstream:~/calico-docker$ sudo dist/calicoctl node
WARNING: Unable to detect the ipip module. Load with `modprobe ipip`
No IP provided. Using detected IP: 172.17.8.10
Calico node is running with id: 3c098a2bbd161308fbefc78ccc675f0b426e581cfd637341d3b7b848bb0a3c1d
gulfstream@gulfstream:~/calico-docker$ docker exec test1 ping 192.168.0.2
PING 192.168.0.2 (192.168.0.2): 56 data bytes
64 bytes from 192.168.0.2: seq=0 ttl=63 time=0.180 ms
64 bytes from 192.168.0.2: seq=1 ttl=63 time=0.272 ms
^Cgulfstream@gulfstream:~/calico-docker$ docker stop calico-node
calico-node
gulfstream@gulfstream:~/calico-docker$ docker exec test1 ping 192.168.0.2
PING 192.168.0.2 (192.168.0.2): 56 data bytes
64 bytes from 192.168.0.2: seq=0 ttl=63 time=0.293 ms
64 bytes from 192.168.0.2: seq=1 ttl=63 time=0.262 ms
```

**Comment by tomdee** [comment] 2015-09-30 21:37
Actually ignore that. I think the problem is the `ExecStop=/opt/bin/calicoctl node stop --force` line in your unit file. 

`node stop` will remove **all** config for that host from etcd. Therefore, that command is deleting all the endpoints from etcd. Normally, you wouldn't be able to run it because there are still endpoints configured, but because you're passing in --force, it's wiping those out too.

I think a better option would be run `docker stop`, rather than `calicoctl node stop` in your ExecStop.

**Comment by hectorj2f** [comment] 2015-10-02 09:18
Thanks @tomdee I'll try this option.

**Comment by hectorj2f** [comment] 2015-10-02 09:47
@tomdee I tried to replace `calicoctl node stop` by `docker stop` and at the beginning seems to keep the iptable definitions of existing container. Howeave after a while they are gone again.. :-(.

**Comment by hectorj2f** [comment] 2015-10-05 16:35
@tomdee Do you have any workaround ? The `docker stop` alternative doesn't seem to work.

**Comment by tomdee** [comment] 2015-10-05 17:51
Is the current problem just that the iptables rules are disappearing (after a while)? or is there something else?

**Comment by hectorj2f** [comment] 2015-10-05 17:53
Well, if all the iptables definitions are gone.. the communication between containers fails as those are not defined anymore. Consequently, we're forced to re-register all the containers again.

**Comment by tomdee** [comment] 2015-10-05 17:55
So are you saying that just running felix again doesn't work?

(It might be worth us continuing this conversation on slack - you can sign up here for realtime support :smile: https://calicousers-slackin.herokuapp.com/)

**Comment by fasaxc** [comment] 2015-10-06 07:50
@tomdee @hectorj2f  Sorry, missed the notification when you tagged me.  Felix doesn't remove iptables definitions when it exits.  That is part of our "graceful restart" strategy; we leave the dataplane as-is when we exit and then resynchronise it when we're restarted.

When Felix starts again, it will go through a synchronisation process.  

* First, it downloads the latest snapshot of the configuration from etcd.
* Then, it applies that snapshot to iptables.
* Finally, after about 30s, it does a cleanup to remove any iptables chains that were from the previous run but are no longer suppose to be there.

You may be seeing the cleanup remove the old iptables chains; however (unless there's a bug), Felix will only remove those chains if the endpoints have been deleted while Felix was down.

To confirm, I suggest doing `etcdctl ls --recursive` before and after stopping/starting the node.  That will show if any keys are being deleted from etcd.

**Comment by fasaxc** [comment] 2015-10-06 08:00
If the iptables rules are disappearing while Felix is down then something else on the system must be removing them.  There's no mechanism to time them out.  If that's the case then that other process is probably fighting with Felix while it is up too (but Felix refreshes the iptables state regularly while it is up to be robust to accidental iptables breakage).

**Comment by hectorj2f** [comment] 2015-10-06 13:28
Hi @fasaxc, 

As I mentioned in this issue, we had a problem with iptables definitions being deleted of container that were still running. There is a way to reproduce the issue and it is described at the beginning of it. I'd like to know if you were able to reproduce it.

On the other hand, I tried replacing the `calicoctl node stop --force` command in my systemd unit by a `docker stop calico-node` as suggested by @tomdee. Initially, I could see how the iptables definitions remained for about approx. 30s, then all of them were gone. That might fit to what  you mentioned 'after about 30s, it does a cleanup to remove any iptables chains that were from the previous run but are no longer supposed to be there.`. However the problem for us is that the containers are still there alive, and we have to re-register them all, again.

Before/After the restart operation, the `etcd` calico information is still there but I don't see where the specific `ip-rules-profile` keys are stored. I can see the assignment of IPs, Profiles, Tags, Rules but nothing else. Where is this snapshot info supposed to be stored ? I think that this restore operation is not being executed `downloads the latest snapshot of the configuration from etcd.` or there isn't any information matching the rule `endpointIP-iptable-profile-rule`.

If you want we talk via Slack @fasaxc :)

**Comment by hectorj2f** [comment] 2015-10-17 15:30
Hi guys. Do you have any news regarding this issue ?

**Comment by tomdee** [comment] 2015-10-18 06:12
No news I'm afraid. We've not encountered this issue ourselves or from anyone else so we'll need to get a local repro before we can fix. Do you think this should repro the problem?
* Run CoreOS
* Run `sudo calicoctl node`
* Create a container and network it with calico (observe that it has iptables rules)
* Run `docker stop calico-node`
* Wait 30s then I should see that the iptables rules have disappeared?

**Comment by hectorj2f** [comment] 2015-10-18 10:12
Yes @tomdee, that'd be the ideal scenario to reproduce this problem.

**Comment by tomdee** [comment] 2015-10-19 17:29
I'm unable to repro this issue using the steps above with calico-docker 0.8 and CoreOS Alpha 835.1.0

Can you try again to see if you can repro it and let us know how you did it and what versions you used?

**Comment by hectorj2f** [comment] 2015-10-22 11:06
thanks @tomdee!. I'll try to reproduce it with this version.

**Comment by tomdee** [comment] 2015-11-06 01:22
@hectorj2f We're working on making the `node stop` behavior better. The improvements should be in the next release. 

I'm going to close this issue, but please do reopen it if you can repro the problem.

**Closed by tomdee** 2015-11-06 01:22 UTC
Labels: documentation

**Comment by hectorj2f** [comment] 2015-11-06 09:35
@tomdee Thanks! sure I'd test the latest version when possible :+1:
