### ISSUE TITLE
Can't remove a container from Calico if it's already been killed and rmed from Docker

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calico-docker#501] opened 2015-09-25 17:13 UTC
I wanted to stop a Calico node (`calicoctl node stop`), but it complained (rightly) that there was still a workload running.  I `docker kill`ed and `docker rm`ed the container, but it remained in calicoctl.

I then tried `calicoctl container remove <name>`, `calicoctl container remove <short id from docker PS>` and `calicoctl container remove <long workload id from calicoctl endpoint show --detailed>`, but in all cases it returned "Container <identifier> was not found.".

I was using calico-docker 0.6.0, having followed the Ubuntu manual install process.  I was able to `calicoctl node stop --force`, but it should be possible to remove a container from Calico without doing this.

**Comment by TrimBiggs** [comment] 2015-09-25 18:26
This is a duplicate of #492.

**Comment by tomdee** [comment] 2015-09-28 23:02
Actually, not quite a dupe.

This is about calicoctl container remove not being able to find IDs when the container has been removed from docker. The other is about IPs.

**Closed** 2015-10-16 20:53 UTC
Labels: bug
