### ISSUE TITLE
Container looses internet access when added manually to calico network

### ISSUE THREAD

**Issue by flipchart** [projectcalico/calico-docker#409] opened 2015-08-03 19:26 UTC
Not sure if this is expected behavior, but I'm pretty sure it worked (as in I had internet access after adding the container to the network) in a previous release (before version 0.4.7)

I start a container with docker, leaving the default networking, and not using powerstrip or libnetwork
`docker run -dti --name test ubuntu`

I confirm the container can access the internet
`docker exec test ping google.com`
```
PING google.com (197.84.128.39) 56(84) bytes of data.
64 bytes from 197.84.128.39: icmp_seq=1 ttl=55 time=20.8 ms
64 bytes from 197.84.128.39: icmp_seq=2 ttl=55 time=18.1 ms
```

I add the container to the calico network
`./calicoctl container add test 192.168.0.2`

I note now that the container cannot access the internet as the ping command does not print any output (or eventually prints `ping: unknown host google.com`)

calicoctl version 0.5.3

**Comment by spikecurtis** [comment] 2015-08-03 21:18
@flipchart I suspect what's happening here is that your container can send packets to the Internet just fine, but the replies aren't routed back to the container.  You can turn on NAT for outbound traffic, which should allow outbound Internet access:  https://github.com/Metaswitch/calico-docker/blob/master/docs/FAQ.md#how-can-i-enable-nat-for-outgoing-traffic-from-containers-with-private-ip-addresses

**Comment by flipchart** [comment] 2015-08-04 03:11
Outgoing NAT doesn't seem to have resolved the issue. I used the following commands:

```
./calicoctl pool add 10.0.0.1/16 --nat-outgoing
docker run -dti --name nat ubuntu
./calicoctl container add nat 10.0.0.1
docker exec nat ping google.com
```

No output from the last one. I assigned a profile to the container as well which allowed everything. 

After I had run the above tests, I decided to remove the container from the calico network (`calicoctl container remove nat`) to see if internet connectivity was restored, but it was *not*. I had a look at the output of `ip route` for the newly created container (before adding to the calico network), when the container had been added to the calico network, and then after the container had been removed from the calico network. See output below:

Before calico
```
default via 172.17.42.1 dev eth0
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.9
```

After calico
```
default via 10.0.2.15 dev eth1
10.0.2.15 dev eth1  scope link
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.9
```

After removing from calico
```
172.17.0.0/16 dev eth0  proto kernel  scope link  src 172.17.0.9
```

So I don't get my default gateway back after removing from calico which could be why I can't get internet access after leaving the calico network. My understanding and experience with networking is very limited, especially with Linux so forgive me if I'm showing expected behavior as something strange :) However, I believe that adding and removing a container from the calico network should be reverse operations and leave the container in its original state when both have been performed successively.

**Comment by spikecurtis** [comment] 2015-08-04 15:39
@flipchart thanks for the update.  Let's try to divide and conquer.  You can't ping google.com; I'm interested if it's DNS failing, connectivity to the Internet failing, or both.

Can you ping 8.8.8.8?  If so, then we're just looking at a DNS resolution issue.

From within the container, what's inside `resolv.conf`?  e.g.

    cat /etc/resolv.conf

**Comment by flipchart** [comment] 2015-08-04 17:11
Thanks for the response. I've run the commands you requested, but to no avail. I ran them with containers on both a `--nat-outgoing` pool and regular pool with the same results

So probably not a DNS issue (alone). Below is the result after adding to the calico network
```
root@5ac2f4ffadd9:/# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
27 packets transmitted, 0 received, 100% packet loss, time 26001ms
```

Below output is received no matter when run (before `calicoctl container add`, after adding, and after removing)
```
root@5ac2f4ffadd9:/# cat /etc/resolv.conf
# This file is managed by systemd-resolved(8). Do not edit.
#
# Third party programs must not access this file directly, but
# only through the symlink at /etc/resolv.conf. To manage
# resolv.conf(5) in a different way, replace the symlink by a
# static file or a different symlink.

nameserver 10.0.2.3
```

I didn't mention it before, but my environment is Windows 10, Vagrant 1.7.4, VirtualBox 5.0.0, CoreOS 717.3.0 guest, and docker:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2-dirty
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64

**Comment by tomdee** [comment] 2015-08-14 00:39
Hi @flipchart I've just reproed your issue locally, but I'm still not sure what's going on. I'm fairly certain there's a bug here so I'll continue looking at it tomorrow and try to get a fix in ASAP.

**Comment by TrimBiggs** [comment] 2015-08-27 00:16
Hi @flipchart,

I looked into this a bit more.  The issue is that you have not set up a security profile to use with your container. 

When a container is added to Calico, Calico takes over all networking.  The container cannot send or receive traffic until it has been assigned a security profile.  You can create a profile and assign it to the container.  By default, the profile will allow the container to send outbound traffic anywhere, but the container will only be able to receive traffic from other containers that have been assigned the profile.  

Using NAT, as Spike mentioned above, will allow outbound internet access once you have a profile assigned.  

Here's an example:
```
calicoctl node
docker run -dti --name test ubuntu
docker exec test ping -c 3 8.8.8.8
# PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
# 64 bytes from 8.8.8.8: icmp_seq=1 ttl=56 time=5.28 ms
# 64 bytes from 8.8.8.8: icmp_seq=2 ttl=56 time=4.66 ms
# 64 bytes from 8.8.8.8: icmp_seq=3 ttl=56 time=4.84 ms

calicoctl pool add 10.0.0.1/16 --nat-outgoing
calicoctl container add test 10.0.0.1
docker exec test ping -c 3 8.8.8.8
# No connectivity, let's add a profile

calicoctl profile add PROF_TEST
calicoctl container test profile set PROF_TEST
docker exec test ping -c 3 8.8.8.8
# PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
# 64 bytes from 8.8.8.8: icmp_seq=1 ttl=56 time=4.69 ms
# 64 bytes from 8.8.8.8: icmp_seq=2 ttl=56 time=5.14 ms
# 64 bytes from 8.8.8.8: icmp_seq=3 ttl=56 time=4.79 ms
```

Let me know if this works!

**Comment by tomdee** [comment] 2015-09-02 16:37
I can no longer repro the problem so closing. @flipchart please let us know if you're still hitting this issue and we'll reopen and investigate further.

**Closed by tomdee** 2015-09-02 16:37 UTC
